on:
  workflow_call:
    inputs:
      base_os:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          driver: docker

      - name: Build base
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./base/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/base:${{inputs.base_os}}
          build-args: |
            JITSI_RELEASE=unstable

      - name: Build base-java
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./base-java/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/base-java:${{inputs.base_os}}

      - name: Build jibri
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./jibri/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/jibri:${{inputs.base_os}}

      - name: Build jicofo
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./jicofo/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/jicofo:${{inputs.base_os}}

      - name: Build jigasi
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./jigasi/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/jigasi:${{inputs.base_os}}

      - name: Build jvb
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./jvb/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/jvb:${{inputs.base_os}}

      - name: Build prosody
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./prosody/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/prosody:${{inputs.base_os}}

      - name: Build web
        uses: docker/build-push-action@v2
        env:
          BASE_OS: ${{inputs.base_os}}
        with:
          file: ./web/Dokerfile.${{inputs.base_os}}
          load: true
          tags: |
            jitsi/web:${{inputs.base_os}}
