name: CI Test Build (debian)

on:
  pull_request:
  push:
    branches:
    - master
    paths:
    - '**/Dockerfile.debian'
    - '**/rootfs/**'

jobs:
  build:
    uses: ./.github/workflows/common.yaml
    with:
      base_os: debian
